version: '3'

services:

  rabbit:
    image: rabbitmq:3
    ports:
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=some_secret_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminPass


